{{- if .Values.postsync.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: phylum-init
  namespace: app-common-port
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/hook: PostSync
  labels:
    app.kubernetes.io/name: postsync-pod
spec:
  containers:
  - name: myapp-container
    image: registry.access.redhat.com/ubi8/ubi
    command: ['bash', '-c', 'sleep 3 ; echo Run phylm scripts here']
    imagePullPolicy: Always
  restartPolicy: "Never"
  {{- end }}